name: CI/CD Pipeline (Python)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run tests
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # Step 5: Upload test results (optional)
      - name: Upload test results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./tests
