name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install pytest
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Step 4: Run tests or just run your app
      - name: Run tests
        run: |
          pytest test_app.py || python app.py
